name: Typos
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  typos:
    name: spell check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@master
